export const ACTION_TYPES = {
  TOGGLE_SELECT_ITEM_ID: 'TOGGLE_SELECT_ITEM_ID',
  UPDATE_SELECT_IDS_LIST: 'UPDATE_SELECT_IDS_LIST',
  SET_HISTORY_ARROW: 'SET_HISTORY_ARROW',
  SET_SELECTED_FROM_HISTORY: 'SET_SELECTED_FROM_HISTORY',
  SET_HISTORY_BACK: 'SET_HISTORY_BACK',
  SET_HISTORY_NEXT: 'SET_HISTORY_NEXT',
  INIT_HISTORY: 'INIT_HISTORY',
};
