export const BREEDS_ACTION_TYPES = {
  GET_LIST_ALL_BREEDS_START: 'GET_LIST_ALL_BREEDS_START',
  GET_LIST_ALL_BREEDS_SUCCESS: 'GET_LIST_ALL_BREEDS_SUCCESS',
  GET_LIST_ALL_BREEDS_ERROR: 'GET_LIST_ALL_BREEDS_ERROR',
};
