export const ACTION_TYPES = {
  GENERATE_NEW_ARRAY: 'GENERATE_NEW_ARRAY',
  SORT_BY_SPECTRUM: 'SORT_BY_SPECTRUM',
  SET_SORTED_ARRAY: 'SET_SORTED_ARRAY',
  SET_SORTED_PARAM_VALUE: 'SET_SORTED_PARAM_VALUE',
};
