export const ACTION_TYPES = {
  GENERATE_NEW_ARRAY: 'GENERATE_NEW_ARRAY',
  GET_SORTED_ARRAY: 'GET_SORTED_ARRAY',
  GET_RESTRUCTURATED_ARRAY: 'GET_RESTRUCTURATED_ARRAY',
  SORT_BY_SPECTRUM: 'SORT_BY_SPECTRUM',
  SET_SORTED_ARRAY: 'SET_SORTED_ARRAY',
  SET_SORTED_PARAM_VALUE: 'SET_SORTED_PARAM_VALUE',
  START_GENERATE_NEW_ARRAY: 'START_GENERATE_NEW_ARRAY',
  END_GENERATE_NEW_ARRAY: 'END_GENERATE_NEW_ARRAY',
};
