export const BREEDS_IMAGES_ACTION_TYPES = {
  GET_BREEDS_IMAGES_START: 'GET_BREEDS_IMAGES_START',
  GET_BREEDS_IMAGES_SUCCESS: 'GET_BREEDS_IMAGES_SUCCESS',
  GET_BREEDS_IMAGES_ERROR: 'GET_BREEDS_IMAGES_ERROR',

  GET_BREED_IMAGES_START: 'GET_BREED_IMAGES_START',
  GET_BREED_IMAGES_SUCCESS: 'GET_BREED_IMAGES_SUCCESS',
  GET_BREED_IMAGES_ERROR: 'GET_BREED_IMAGES_ERROR',

  RESET_IMAGES: 'RESET_IMAGES',
};
